<?php

if(isset($_REQUEST['action']) && $_REQUEST['action']=="getReqDet")
{
    $req_id=$_REQUEST['id'];
    
    $sql="select id,description, vm.company_name cname,pm.project_name,pb.block_name,ps.structure_name,concat(ud.name,' ',last_name) gname
                        FROM requisitions r 
                        LEFT JOIN vendor_master vm on vm.vendor_id=r.vendor_id 
                        LEFT JOIN project_master pm on pm.project_id=r.project_id 
                        LEFT JOIN project_blocks pb on pb.block_id=r.block_id 
                        LEFT JOIN project_structures ps on ps.str_id=r.structure_id   
                        LEFT JOIN user_details ud on ud.sl_no =r.added_by
                        where r.id ='".$req_id."'";    
                   // echo $sql;
    $r_q = mysql_query($sql);
    $r_row = mysql_fetch_object($r_q);
?>
<div class="panel panel-transparent">
                <div class="panel-heading">
                        <span class="panel-title">Requisition No. <?=$r_row->id?></span>
                </div>
                <div class="panel-body">
                    <table class="table">
                        <tr><td>Description</td><td><?php echo stripslashes($r_row->description) ?></td></tr>
                        <tr><td>Contractor Name :</td><td><?php echo stripslashes($r_row->project_name) ?></td></tr>
                        <tr><td>Location</td><td><?php echo stripslashes($r_row->project_name) ?></td></tr>
                        <tr><td>Block Name</td><td><?php echo stripslashes($r_row->block_name) ?></td></tr>
                        <tr><td>Structure</td><td><?php echo stripslashes($r_row->structure_name) ?></td></tr>
                        <tr><td>Generated By</td><td><?php echo stripslashes($r_row->gname) ?></td></tr>
                    </table>
                    <div style="">
                        <?php
                        $outfile="";                
                        
                        $q=$conn->prepare("SELECT DISTINCT rd.item_desc,
                                    vwrd.rate,
                                    vwrd.qty,
                                    vwrd.item_record_id,
                                    (vwrd.rate*vwrd.qty) amt,
                                    vm.company_name vname,
                                    u.unit_name,
                                    concat(ud.name,' ',ud.last_name) generated_by,
                                    vwrd.discount 
                                    #vwrd.description
                        FROM vendor_wise_requisition_details vwrd
                        INNER JOIN requisition_details rd ON rd.req_id=vwrd.req_id AND vwrd.item_record_id=rd.id
                        LEFT JOIN requisitions r ON r.id=vwrd.req_id
                        LEFT JOIN vendor_master vm ON vm.vendor_id = vwrd.vendor_id
                        LEFT JOIN user_details ud ON ud.sl_no=vwrd.entry_by
                        LEFT JOIN units u ON u.id=rd.item_unit
                        WHERE r.id='".$req_id."'
                        ORDER BY item_desc,vwrd.vendor_id  "); 
                
                
                $q->execute();
		$q_row = $q->fetchAll(PDO::FETCH_ASSOC);
                //echo "<pre>";                print_r($q_row ); die;
                $q2=$conn->prepare("SELECT distinct rd.item_desc,vwrd.qty,u.unit_name
                        FROM requisitions r                        
                        INNER JOIN requisition_details rd on r.id=rd.req_id
                        INNER JOIN vendor_wise_requisition_details vwrd on r.id=vwrd.req_id and rd.id=vwrd.item_record_id
                        LEFT JOIN vendor_master vm on vm.vendor_id = vwrd.vendor_id
                        LEFT JOIN units u on u.id=rd.item_unit                        
                        where r.id='".$req_id."'"
                        . "ORDER BY item_desc,vwrd.vendor_id ");
                
                $q2->execute();
		$q2_row = $q2->fetchAll(PDO::FETCH_ASSOC);                
		$output .='</table>';
                
                $my_array2=array();
                for($i=0;$i<count($q2_row);$i++)
                {
                    $my_array2['qty'][] =$q2_row[$i]['qty'];                    
                    $my_array2['unit'][] =$q2_row[$i]['unit_name'];  
                }
                
		//echo "<pre>";
                //print_r($my_array2); die;
                $my_array=array();
                $vendors=array();
                $items=array();
                $description=array();
               
                for($i=0;$i<count($q_row);$i++)
                {
                    if(!in_array($q_row[$i]['vname'], $vendors))
                    {
                        $vendors[]=$q_row[$i]['vname'];
                    }
                    if(!in_array($q_row[$i]['item_desc'], $items))
                    {
                        $items[]=$q_row[$i]['item_desc'];
                    }
                    $my_array[$q_row[$i]['item_desc']][$q_row[$i]['vname']]['rate'] =$q_row[$i]['rate'];                    
                    $my_array[$q_row[$i]['item_desc']][$q_row[$i]['vname']]['qty'] =$q_row[$i]['qty'];
                    $my_array[$q_row[$i]['item_desc']][$q_row[$i]['vname']]['amt'] =$q_row[$i]['amt'];
                    $my_array[$q_row[$i]['item_desc']][$q_row[$i]['vname']]['discount'] =$q_row[$i]['discount'];
                    //$description[$q_row[$i]['vname']].=" ".$q_row[$i]['description'];
                }
                $output .='<br/><br/>';
                $output .='<table width="90%"  class="table" cellspacing="0" cellpadding="4" border="1">';                
               // print_r($my_array); 
               // print_r($vendors);
               // print_r($items);
                //print_r($description); die;
                //echo "<pre>";
                $output .='<tr><td colspan="3">&nbsp;</td>'; 
                for($i=0;$i<count($vendors);$i++)
                {
                    $output .='<th colspan="3">'.$vendors[$i].'</th>'; 
                }
                $output .='</tr>'; 
                $output .='<tr>';
                $output .='<th> Material Desc.</th>';
                $output .='<th>Qty</th>';                
                $output .='<th>Unit</th>';
                for($i=0;$i<count($vendors);$i++)
                {
                //    $output .='<th>Qty</th>';
                    $output .='<th>Rate</th>';
                    $output .='<th>Dis</th>';
                    $output .='<th>Amt</th>';
                }
                $output .='</tr>'; 
                $r=0;
                $ven_amt_total=array();
                foreach ($my_array as $k1 => $v1) 
                {
                    //print_r($my_array2);
                    $output .='<tr>'; 
                    $output .='<th>'.$k1.'</th>';
                    //echo $r."##".$my_array2[$r]['qty'][$r]."<br>";
                    $output.='<th>'.$my_array2['qty'][$r].'</th>';                    
                    $output.='<th>'.$my_array2['unit'][$r].'</th>';
                    //print_r($v1);
                    foreach ($v1 as $k2 => $v2) 
                    {
                        
                     //   $output .='<td>'.$v1[$k2]['qty'].'</td>';                     
                        //echo $v1[$k2]['amt']."<br>"; 
                        $output .='<th>'.$v1[$k2]['rate'].'</th>';
                        $output.='<th>'.$v1[$k2]['discount'].'</th>';
                        $output .='<th>'.($v1[$k2]['amt']-$v1[$k2]['discount']).'</th>';                        
                        
                        $ven_amt_total[$k2]+=($v1[$k2]['amt']-$v1[$k2]['discount']);
                    }
                    $output .='</tr>';      
                    $r++;
                }
                $output .='<tr>';      
                $output .='<td colspan="3">&nbsp;</td>';     
                
                $q2=$conn->prepare("SELECT distinct rd.item_desc,vwrd.qty,u.unit_name
                        FROM requisitions r                        
                        INNER JOIN requisition_details rd on r.id=rd.req_id
                        INNER JOIN vendor_wise_requisition_details vwrd on r.id=vwrd.req_id and rd.id=vwrd.item_record_id
                        LEFT JOIN vendor_master vm on vm.vendor_id = vwrd.vendor_id
                        LEFT JOIN units u on u.id=rd.item_unit                        
                        where r.id='".$req_id."'"
                        . "ORDER BY item_desc,vwrd.vendor_id ");
                $q2->execute();
		$q2_row = $q2->fetchAll(PDO::FETCH_ASSOC);
                
                foreach($ven_amt_total as  $key=>$value)
                {
                $output .='<td colspan="3" style="text-align:right; padding-right:10px">Gross Total : '.$value.'</td>';
                }
                $output .='</tr>';   
                
                $output .='<tr>';      
                $output .='<td colspan="3">&nbsp;</td>'; 
                
                $sql="select rvr.*,vm.company_name,description vname FROM req_vendor_rel rvr "
                        . " LEFT JOIN vendor_master vm on vm.vendor_id=rvr.vendor_id"
                        . " where req_id='".$req_id."' ORDER BY rvr.vendor_id";
                        $q100=$conn->prepare($sql);
                        $q100->execute();
                        $q_row100 = $q100->fetchAll(PDO::FETCH_ASSOC);
                    
                        $sql="select sum(qty*rate-discount) amt,vwrd.vendor_id "
                                . " FROM vendor_wise_requisition_details vwrd "
                                . " where req_id='".$req_id."' "
                                . " group by vwrd.vendor_id"
                                . " order by vwrd.vendor_id";
                        $q101=$conn->prepare($sql);
                        $q101->execute();
                        $q_row101 = $q101->fetchAll(PDO::FETCH_ASSOC);
                    //echo "<pre>";print_r($q_row100); die; 
                        $str="";
                        $net_amt=0;
                        for($n=0;$n<count($q_row100);$n++)
                        {
                            if($q_row100[$n]['discount_type']=="P")
                            {
                                $net_amt=($q_row101[$n]['amt']-($q_row101[$n]['amt']*$q_row100[$n]['discount_amt']/100));
                               $str="Discount Per : ".$q_row100[$n]['discount_amt'].",Net Total : ".$net_amt;
                                
                            }
                            else if($q_row100[$n]['discount_type']=="F")
                            {
                                $net_amt=($q_row101[$n]['amt']-$q_row100[$n]['discount_amt']);
                                $str="Discount Amt : ".$q_row100[$n]['discount_amt'].",Net Total : ".$net_amt;
                            }
                            $output .='<td colspan="3" style="text-align:right; padding-right:10px"> '.$str.'</td>';
                        }
                
                        
                        
                $output .='</tr>';   
                
                $output .='<tr>';      
                $output .='<td colspan="3">&nbsp;</td>'; 
                
                for($n=0;$n<count($q_row100);$n++)
                {
                    $output .='<td colspan="3" style="text-align:right; padding-right:10px"> Description : '.$q_row100[$n]['description'].'</td>';
                }
                
                $output .='</tr>';   
                $output .='</table>';
                
                $output .='<tr>';      
                $output .='<td colspan="3">&nbsp;</td>'; 
                
                foreach($description as  $key=>$value)
                {
                $output .='<td colspan="2" style="text-align:right; padding-right:10px"> '.$value.'</td>';
                }
                $output .='</tr>';   
                $output .='</table>';
                
                echo $output;
                        ?>
                    </div>
                </div>
                </div>
<?php
}